{% set version = "2.24" %}

package:
  name: coda
  version: {{ version }}

source:
  url: https://github.com/stcorp/coda/releases/download/{{ version }}/coda-{{ version }}.tar.gz
  sha256: b27073b645b6334a6bd9c5e74912137bfd4bdfd96d475c2de7fc39ef7935128a

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]

  host:
    - python
    - jpeg
    - zlib
    - hdf4
    - hdf5

  run:
    - python
    - cffi  # [python_impl != 'pypy']
    - numpy

test:
  commands:
    - test -f $PREFIX/lib/libcoda$SHLIB_EXT  # [unix]
    - if not exist "%LIBRARY_PREFIX%/lib/libcoda.lib" exit 1  # [win]
    - if not exist "%LIBRARY_PREFIX%/bin/codacmp.exe" exit 1  # [win]
  imports:
    - coda

about:
  home: https://github.com/stcorp/coda
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: COPYING
  summary: CODA is the Common Data Access framework that allows reading of scientific data from various data formats, including structured ascii, structured binary, XML, netCDF, CDF, HDF4, HDF5, GRIB, RINEX and SP3. It provides a single consistent hierarchical view on data independent of the underlying storage format.

extra:
  recipe-maintainers:
    - srepmub
    - svniemeijer
